name: ngdemo7
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
   - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:

  #       - asset: fonts/Schyler-Regular.ttf
